// src/pages/index.js

import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import dynamic from 'next/dynamic';
import { Suspense } from 'react';
import Head from 'next/head';
import Image from 'next/image'; // Using Next.js optimized Image component

// Dynamically import heavy components to improve initial load performance
const Hero = dynamic(() => import('@/components/Hero'), { suspense: true });
const Filter = dynamic(() => import('@/components/Filter'), { suspense: true });
const Globe = dynamic(() => import('@/components/Globe'), { suspense: true });
const HomePageContent = dynamic(() => import('@/components/HomePageContent'), { suspense: true });
const MobileGallery = dynamic(() => import('@/components/MobileGallery'), { suspense: true });
const Faq = dynamic(() => import('@/components/FaqSection/Faq'), { suspense: true });
const Contact = dynamic(() => import('@/components/Contact'), { suspense: true });

// Keywords for SEO by language
const keywordsByLanguage = {
  tr:[
    'Villa satın al Sylvana İstanbul',
'Sylvana İstanbul 4+1 villaları satılık',
'Bahçeşehir İstanbul’da lüks villalar',
'İstanbul modern villa projeleri',
'Sylvana İstanbul İtalyan tasarımı evler',
'İstanbul’da aileler için sıra villalar',
'İstanbul Havaalanı’na yakın villalar',
'Bahçeşehir’de yüksek kaliteli gayrimenkul',
'Afra Park İstanbul villaları satılık',
'Bahçeşehir’de lüks 2+1’den 5+1 villalar',
'Afra Park’ta aile dostu evler',
'Bahçeşehir modern villalar yatırım için',
'İstanbul’da uygun fiyatlı lüks villalar',
'Bahçeşehir’de doğa dostu mülkler',
'İstanbul villa projeleriyle olanaklar',
'Afra Park Bahçeşehir’de satılık villalar',
'Reportage Türkiye lüks gayrimenkuller',
'İstanbul’da modern villa satın al',
'İstanbul’da satılık gayrimenkuller',
'Türkiye’nin en iyi villa projeleri',
'Bahçeşehir villa projeleri',
'İstanbul üniversitelerine yakın gayrimenkuller',
'İstanbul’da lüks gayrimenkul yatırımları',
'İstanbul’da sıra ve müstakil villalar',
'Emlak yatırımı ile Türk vatandaşlığı',
'Türk vatandaşlık programı için villalar',
'İstanbul’da Türk pasaportu için gayrimenkuller',
'Emlak aracılığıyla Türk vatandaşlığı nasıl alınır',
'2024 Türk vatandaşlık yatırım programı',
'İstanbul’da gayrimenkul alarak vatandaşlık',
'Türkiye’de vatandaşlık onaylı villalar',
'Türk vatandaşlığı için minimum yatırım',
'İstanbul’da gayrimenkule yatırım yapılacak en iyi yerler',
'Bahçeşehir’de yüksek ROI’li mülkler',
'İstanbul gayrimenkul yatırım fırsatları',
'2024 Türk gayrimenkul piyasası',
'İstanbul’da uzun vadeli yatırım yapılacak villalar',
'Türkiye’de uygun fiyatlı lüks yatırımlar',
'İstanbul mega projelerine yakın gayrimenkuller',
'Bahçeşehir gayrimenkullerinin kiralık gelir potansiyeli',
'Bahçeşehir İstanbul’da villa satın al',
'İstanbul Kanal projesine yakın mülkler',
'Başakşehir şehir merkezine yakın gayrimenkuller',
'İstanbul’un mega altyapısına yakın evler',
'İstanbul’un en iyi hastanelerine yakın villalar',
'İstanbul’un yeni finansal bölgesine yakınlık',
'İstanbul Yeni Havaalanı’na yakın gayrimenkuller',
'Türk vatandaşlığı yatırım yolu ile kazanma avantajları',
'İstanbul’da gayrimenkul yatırımının avantajları',
'Yatırım yoluyla Türk oturumu güvence altına almak',
'Aileler için Türk gayrimenkulleri',
'Türkiye’deki vergi muafiyetli gayrimenkul yatırımları',
'Yabancılar için İstanbul’da tapulu gayrimenkuller',
'Gayrimenkul yolu ile hızlı Türk pasaportu',
'İstanbul’da hayalinizdeki villayı bugün satın alın',
'İstanbul’un lüks villa projelerine yatırım yapın',
'Bahçeşehir’deki özel gayrimenkulleri keşfedin',
'Türk vatandaşlık yolculuğunuza bizimle başlayın',
'İstanbul’da satılık uygun fiyatlı villalar',
'İstanbul gayrimenkul fırsatları için bizimle iletişime geçin',
'Türk vatandaşlık yatırımları için gayrimenkul uzmanları',
'Yabancı olarak İstanbul’da villa nasıl satın alınır',
'Türk vatandaşlığı almak için yatırım adımları',
'İstanbul 2024’teki en iyi villa projeleri nedir?',
'Türkiye’de gayrimenkul yatırımının iyi bir seçenek olup olmadığı',
'Neden Bahçeşehir gayrimenkul yatırımı için tercih edilmelidir?',
'İstanbul’daki en lüks villa projeleri',
'Türk vatandaşlığına uygun satılık villalar',
'İstanbul’da özel bahçeli villalar',
'Balkonlu ve en-suite banyolu evler',
'İstanbul’da aile dostu olanaklara sahip gayrimenkuller',
'Bahçeşehir’de 7/24 güvenliği olan villalar',
'İstanbul’da çevre dostu villa projeleri',
'Türkiye’deki modern mimari villalar',
'İstanbul’da akıllı ev villa projeleri',
'Türk vatandaşlığı için İstanbul’da lüks villalar satın al',
'Bahçeşehir İstanbul’da uygun fiyatlı aile dostu evler',
'İstanbul’daki en iyi villa projelerine yatırım fırsatları',
'İstanbul’daki yüksek kira getirisi potansiyeline sahip villalar',
  'Dubai\'deki Gayrimenkul Şirketleri',
  'Reportage Properties',
  'Lüks Daireler Abu Dabi',
  'BAE\'deki Emlak Seçenekleri',
  'Lüksü Yeniden Tanımlamak',
  'Deneyimleri Yeniden Tanımlamak',
  'Sığınakları Yeniden Tanımlamak',
  'Evi Yeniden Tanımlamak',
  'Projeler',
  'Topluluklar',
  'Teklifler',
  'Medya Merkezi',
  'Kariyerler',
  'İnşaat Güncellemeleri',
  'Bianca',
  'Lilium',
  'SYLVANA',
  'Verdana',
  'Perla 1',
  'Perla 2',
  'Al Maryah Vista 2',
  'Montenapoleone',
  'DIVA',
  'Rukan Tower',
  'Al Maryah Island',
  'Al Qadisiyyah',
  'Al Raha Beach',
  'Al Reem Island',
  'Bahçeşehir',
  'DIP – Dubai Yatırım Parkı',
  'Downtown Jebel Ali',
  'Abu Dhabi',
  'Dubai',
  'Mısır',
  'Fas',
  'Pakistan',
  'Rusya',
  'Ruanda',
  'Suudi Arabistan',
  'Türkiye',
  'Uganda',
  'https://reportage.com.tr/',
  'Gayrimenkul ve Yatırım Fırsatları',
  'Reportage Türkiye',
  'Lüks Gayrimenkul Geliştirme',
  'Yatırım',
  'İstanbul',
  'Türkiye',
  'Birleşik Arap Emirlikleri',
  'Suudi Arabistan',
  'Mısır',
  'Fas',
  'Rusya',
  'Beyaz Rusya',
  'Uganda',
  'Global Gayrimenkul Geliştirici',
  'Global Gayrimenkul Yatırımcı',
  'Lüks Gayrimenkul İstanbul',
  'Gayrimenkul Pazarı',
  'Afra Park',
  'SYLVANA',
  'Bahçeşehir',
  'Başakşehir',
  'Modern Villa Seçenekleri',
  'Doğa ile İç İçe',
  'Konforlu ve Huzurlu Yaşam',
  'İnşaat Güncellemeleri',
  'Medya Merkezi',
  'Kampanyalar',
  'Yerleşkeler',
  'Projeler',
  'Blog',
  'Bize Ulaşın',

'Türk vatandaşlık yatırımları için gayrimenkul uzmanları'
],

  en: [
    'Buy villas in Sylvana Istanbul',
    'Sylvana Istanbul 4+1 villas for sale',
    'Luxury villas in Bahçeşehir Istanbul',
    'Modern villa projects Istanbul',
    'Sylvana Istanbul Italian design homes',
    'Istanbul row villas for families',
    'Villas near Istanbul Airport',
    'High-end real estate Bahçeşehir',
    'Afra Park Istanbul villas for sale',
    'Luxury 2+1 to 5+1 villas in Bahçeşehir',
    'Family-friendly homes in Afra Park',
    'Bahçeşehir modern villas for investment',
    'Affordable luxury villas in Istanbul',
    'Nature-friendly properties Bahçeşehir',
    'Istanbul villa projects with amenities',
    'Villas in Afra Park Bahçeşehir for sale',
    'Reportage Türkiye luxury properties',
    'Buy modern villas in Istanbul',
    'Istanbul real estate for sale',
    'Best villa projects in Turkey',
    'Bahçeşehir villa developments',
    'Real estate near Istanbul universities',
    'Luxury property investments Istanbul',
    'Row and detached villas in Istanbul',
    'Turkish citizenship by real estate investment',
    'Villas for Turkish citizenship program',
    'Istanbul properties for Turkish passport',
    'How to get Turkish citizenship through property',
    'Turkish citizenship investment program 2024',
    'Buy real estate in Istanbul for citizenship',
    'Citizenship-approved villas in Turkey',
    'Minimum investment for Turkish citizenship',
    'Best places to invest in real estate in Istanbul',
    'High ROI properties in Bahçeşehir',
    'Istanbul real estate investment opportunities',
    'Turkish real estate market 2024',
    'Villas for long-term investment in Istanbul',
    'Affordable luxury investments Turkey',
    'Real estate near Istanbul mega projects',
    'Rental income potential Bahçeşehir properties',
    'Buy villas in Bahçeşehir Istanbul',
    'Properties near Istanbul Canal project',
    'Real estate near Başakşehir city center',
    'Homes near Istanbul’s mega infrastructure',
    'Villas near Istanbul’s top hospitals',
    'Proximity to Istanbul new financial district',
    'Real estate near Istanbul New Airport',
    'Benefits of Turkish citizenship by investment',
    'Advantages of investing in Istanbul properties',
    'How to secure Turkish residency through investment',
    'Turkish real estate for family relocation',
    'Tax-free property investments in Turkey',
    'Freehold properties in Istanbul for expats',
    'Fast-track Turkish passport through real estate',
    'Buy your dream villa in Istanbul today',
    'Invest in Istanbul’s luxury villa projects',
    'Discover exclusive properties in Bahçeşehir',
    'Start your Turkish citizenship journey with us',
    'Affordable villas for sale in Istanbul',
    'Contact us for Istanbul property deals',
    'Real estate experts in Turkish citizenship',
    'How to buy a villa in Istanbul as a foreigner',
    'Steps to acquire Turkish citizenship by investment',
    'What are the best villa projects in Istanbul 2024?',
    'Is real estate a good investment in Turkey?',
    'Why choose Bahçeşehir for property investment?',
    'Top luxury villa projects for sale in Istanbul',
    'Turkish villas for sale with citizenship eligibility',
    'Villas with private gardens in Istanbul',
    'Homes with balconies and ensuite bathrooms',
    'Properties with family-friendly amenities Istanbul',
    'Villas with 24/7 security in Bahçeşehir',
    'Eco-friendly villa projects Istanbul',
    'Modern architecture villas in Turkey',
    'Smart home villas in Istanbul',
    'Buy luxury villas in Istanbul for Turkish citizenship',
    'Affordable family-friendly homes in Bahçeşehir Istanbul',
    'Investment opportunities in Istanbul’s top villa projects',
    'Villas in Istanbul with high rental yield potential',
    'Real estate experts for Turkish citizenship investment',
    'Real Estate Companies in Dubai',
    'Reportage Properties',
    'Luxury Apartments in Abu Dhabi',
    'Property Options in UAE',
    'Redefining Luxury',
    'Redefining Experiences',
    'Redefining Sanctuaries',
    'Redefining Home',
    'Projects',
    'Communities',
    'Offers',
    'Media Center',
    'Careers',
    'Construction Updates',
    'Bianca',
    'Lilium',
    'SYLVANA',
    'Verdana',
    'Perla 1',
    'Perla 2',
    'Al Maryah Vista 2',
    'Montenapoleone',
    'DIVA',
    'Rukan Tower',
    'Al Maryah Island',
    'Al Qadisiyyah',
    'Al Raha Beach',
    'Al Reem Island',
    'Bahçeşehir',
    'DIP – Dubai Investments Park',
    'Downtown Jebel Ali',
    'Abu Dhabi',
    'Dubai',
    'Egypt',
    'Morocco',
    'Pakistan',
    'Russia',
    'Rwanda',
    'Saudi',
    'Türkiye',
    'Uganda',
    'https://reportage.com.tr/',
    'Real Estate and Investment Opportunities',
    'Reportage Türkiye',
    'Luxury Real Estate Development',
    'Investment',
    'Istanbul',
    'Turkey',
    'United Arab Emirates',
    'Saudi Arabia',
    'Egypt',
    'Morocco',
    'Russia',
    'Belarus',
    'Uganda',
    'Global Real Estate Developer',
    'Global Real Estate Investor',
    'Luxury Real Estate Istanbul',
    'Real Estate Market',
    'Afra Park',
    'SYLVANA',
    'Bahçeşehir',
    'Başakşehir',
    'Modern Villa Options',
    'Nature-Integrated Living',
    'Comfortable and Peaceful Living',
    'Construction Updates',
    'Media Center',
    'Campaigns',
    'Campuses',
    'Projects',
    'Blog',
    'Contact Us',
  ],
  ar: [
    'شراء فيلات في سيلفانا إسطنبول',
    'فيلات سيلفانا إسطنبول 4+1 للبيع',
    'فيلات فاخرة في بهتشه شهير إسطنبول',
    'مشاريع الفيلات الحديثة في إسطنبول',
    'منازل سيلفانا إسطنبول بتصميم إيطالي',
    'فيلات إسطنبول المتلاصقة للعائلات',
    'فيلات بالقرب من مطار إسطنبول',
    'عقارات فاخرة في بهتشه شهير',
    'فيلات أفرا بارك إسطنبول للبيع',
    'فيلات فاخرة 2+1 إلى 5+1 في بهتشه شهير',
    'منازل صديقة للعائلات في أفرا بارك',
    'فيلات بهتشه شهير الحديثة للاستثمار',
    'فيلات فاخرة ميسورة التكلفة في إسطنبول',
    'عقارات صديقة للطبيعة في بهتشه شهير',
    'مشاريع فيلات في إسطنبول مع وسائل الراحة',
    'فيلات في أفرا بارك بهتشه شهير للبيع',
    'عقارات فاخرة من ريبورتاج تركيا',
    'شراء فيلات حديثة في إسطنبول',
    'عقارات إسطنبول للبيع',
    'أفضل مشاريع الفيلات في تركيا',
    'تطورات الفيلات في بهتشه شهير',
    'عقارات بالقرب من الجامعات في إسطنبول',
    'استثمارات عقارية فاخرة في إسطنبول',
    'فيلات متلاصقة ومنفصلة في إسطنبول',
    'الجنسية التركية من خلال الاستثمار العقاري',
    'فيلات لبرنامج الجنسية التركية',
    'عقارات إسطنبول للحصول على جواز السفر التركي',
    'كيفية الحصول على الجنسية التركية من خلال العقار',
    'برنامج الاستثمار للحصول على الجنسية التركية 2024',
    'شراء عقار في إسطنبول للحصول على الجنسية',
    'فيلات معتمدة للجنسية في تركيا',
    'الحد الأدنى للاستثمار للحصول على الجنسية التركية',
    'أفضل الأماكن للاستثمار العقاري في إسطنبول',
    'عقارات ذات عائد مرتفع في بهتشه شهير',
    'فرص الاستثمار العقاري في إسطنبول',
    'سوق العقارات التركي 2024',
    'فيلات للاستثمار طويل الأجل في إسطنبول',
    'استثمارات فاخرة ميسورة التكلفة في تركيا',
    'عقارات بالقرب من المشاريع الضخمة في إسطنبول',
    'إمكانات دخل الإيجار لعقارات بهتشه شهير',
    'شراء فيلات في بهتشه شهير إسطنبول',
    'عقارات بالقرب من مشروع قناة إسطنبول',
    'عقارات بالقرب من مركز مدينة باشاك شهير',
    'منازل بالقرب من بنية إسطنبول التحتية الضخمة',
    'فيلات بالقرب من مستشفيات إسطنبول الكبرى',
    'القرب من الحي المالي الجديد في إسطنبول',
    'عقارات بالقرب من مطار إسطنبول الجديد',
    'فوائد الجنسية التركية من خلال الاستثمار',
    'مزايا الاستثمار في عقارات إسطنبول',
    'كيفية تأمين الإقامة التركية من خلال الاستثمار',
    'العقارات التركية للانتقال العائلي',
    'استثمارات عقارية معفاة من الضرائب في تركيا',
    'عقارات ملكية حرة في إسطنبول للمغتربين',
    'جواز سفر تركي سريع من خلال العقارات',
    'اشترِ فيلتك الفاخرة في إسطنبول اليوم',
    'استثمر في مشاريع الفيلات الفاخرة في إسطنبول',
    'اكتشف عقارات حصرية في بهتشه شهير',
    'ابدأ رحلتك للحصول على الجنسية التركية معنا',
    'فيلات ميسورة التكلفة للبيع في إسطنبول',
    'اتصل بنا لصفقات العقارات في إسطنبول',
    'خبراء العقارات في الجنسية التركية',
    'كيفية شراء فيلا في إسطنبول كأجنبي',
    'خطوات الحصول على الجنسية التركية من خلال الاستثمار',
    'ما هي أفضل مشاريع الفيلات في إسطنبول 2024؟',
    'هل العقارات استثمار جيد في تركيا؟',
    'لماذا تختار بهتشه شهير للاستثمار العقاري؟',
    'أفضل مشاريع الفيلات الفاخرة للبيع في إسطنبول',
    'فيلات تركية للبيع مع أهلية الجنسية',
    'فيلات مع حدائق خاصة في إسطنبول',
    'منازل مع شرفات وحمامات داخلية',
    'عقارات مع وسائل راحة صديقة للعائلات في إسطنبول',
    'فيلات مع أمن على مدار الساعة في بهتشه شهير',
    'مشاريع فيلات صديقة للبيئة في إسطنبول',
    'فيلات معمارية حديثة في تركيا',
    'فيلات ذكية في إسطنبول',
    'شراء فيلات فاخرة في إسطنبول للحصول على الجنسية التركية',
    'منازل صديقة للعائلات بأسعار معقولة في بهتشه شهير إسطنبول',
    'فرص الاستثمار في أفضل مشاريع الفيلات في إسطنبول',
    'فيلات في إسطنبول مع إمكانات عالية للعائد الإيجاري',
    'شركات العقارات في دبي',
    'عقارات ريبورتاج',
    'شقق فاخرة في أبوظبي',
    'خيارات العقارات في الإمارات',
    'إعادة تعريف الفخامة',
    'إعادة تعريف التجارب',
    'إعادة تعريف الملاذات',
    'إعادة تعريف المنزل',
    'المشاريع',
    'المجتمعات',
    'العروض',
    'مركز الإعلام',
    'الوظائف',
    'تحديثات البناء',
    'بيانكا',
    'ليليوم',
    'سلفانا',
    'فيردانا',
    'بيرلا 1',
    'بيرلا 2',
    'المرج 2',
    'مونتينابوليون',
    'ديفا',
    'برج روكان',
    'جزيرة المارية',
    'القديسية',
    'شاطئ الرحة',
    'جزيرة الريم',
    'باهتشه شهير',
    'DIP – دبي بارك الاستثماري',
    'وسط مدينة جبل علي',
    'أبوظبي',
    'دبي',
    'مصر',
    'المغرب',
    'باكستان',
    'روسيا',
    'رواندا',
    'السعودية',
    'تركيا',
    'أوغندا',
    'https://reportage.com.tr/',
    'فرص العقارات والاستثمار',
    'ريبورتاج تركيا',
    'تطوير العقارات الفاخرة',
    'استثمار',
    'إسطنبول',
    'تركيا',
    'الإمارات العربية المتحدة',
    'المملكة العربية السعودية',
    'مصر',
    'المغرب',
    'روسيا',
    'روسيا البيضاء',
    'أوغندا',
    'المطور العقاري العالمي',
    'المستثمر العقاري العالمي',
    'العقارات الفاخرة في إسطنبول',
    'سوق العقارات',
    'أفرا بارك',
    'سلفانا',
    'باهتشه شهير',
    'باشاك شهير',
    'خيارات الفلل الحديثة',
    'الحياة المتكاملة مع الطبيعة',
    'الحياة المريحة والهادئة',
    'تحديثات البناء',
    'مركز الإعلام',
    'الحملات',
    'المجمعات',
    'المشاريع',
    'المدونة',
    'اتصل بنا',
    'خبراء العقارات للاستثمار في الجنسية التركية'
],
de: [
  'Villen zum Kauf in Sylvana Istanbul',
  'Sylvana Istanbul 4+1 Villen zum Verkauf',
  'Luxusvillen in Bahçeşehir Istanbul',
  'Moderne Villa-Projekte Istanbul',
  'Sylvana Istanbul italienische Designhäuser',
  'Reihenhäuser in Istanbul für Familien',
  'Villen in der Nähe des Flughafens Istanbul',
  'Luxuriöse Immobilien in Bahçeşehir',
  'Afra Park Istanbul Villen zum Verkauf',
  'Luxusvillen 2+1 bis 5+1 in Bahçeşehir',
  'Familienfreundliche Häuser in Afra Park',
  'Moderne Villen in Bahçeşehir für Investitionen',
  'Erschwingliche Luxusvillen in Istanbul',
  'Naturfreundliche Immobilien in Bahçeşehir',
  'Villa-Projekte in Istanbul mit Annehmlichkeiten',
  'Villen in Afra Park Bahçeşehir zum Verkauf',
  'Reportage Türkiye Luxusimmobilien',
  'Moderne Villen in Istanbul kaufen',
  'Immobilien in Istanbul zum Verkauf',
  'Beste Villa-Projekte in der Türkei',
  'Villenentwicklungen in Bahçeşehir',
  'Immobilien in der Nähe von Universitäten in Istanbul',
  'Luxusimmobilieninvestitionen in Istanbul',
  'Reihen- und freistehende Villen in Istanbul',
  'Türkische Staatsbürgerschaft durch Immobilieninvestitionen',
  'Villen für das türkische Staatsbürgerschaftsprogramm',
  'Immobilien in Istanbul für den türkischen Pass',
  'Wie man die türkische Staatsbürgerschaft durch Immobilien erwirbt',
  'Türkisches Staatsbürgerschaftsinvestitionsprogramm 2024',
  'Immobilien in Istanbul für die Staatsbürgerschaft kaufen',
  'Staatsbürgerschaftsgeprüfte Villen in der Türkei',
  'Mindestinvestition für die türkische Staatsbürgerschaft',
  'Beste Orte, um in Immobilien in Istanbul zu investieren',
  'Immobilien mit hoher Rendite in Bahçeşehir',
  'Immobilieninvestitionsmöglichkeiten in Istanbul',
  'Immobilienmarkt in der Türkei 2024',
  'Villen für langfristige Investitionen in Istanbul',
  'Erschwingliche Luxusinvestitionen in der Türkei',
  'Immobilien in der Nähe von Großprojekten in Istanbul',
  'Mietpotenzial von Bahçeşehir Immobilien',
  'Villen kaufen in Bahçeşehir Istanbul',
  'Immobilien in der Nähe des Istanbul Kanalprojekts',
  'Immobilien in der Nähe des Stadtzentrums von Başakşehir',
  'Häuser in der Nähe von Istanbuls Megainfrastruktur',
  'Villen in der Nähe von Istanbuls größten Krankenhäusern',
  'Nähe zum neuen Finanzdistrikt in Istanbul',
  'Immobilien in der Nähe des neuen Flughafens Istanbul',
  'Vorteile der türkischen Staatsbürgerschaft durch Investitionen',
  'Vorteile der Investition in Immobilien in Istanbul',
  'Wie man die türkische Aufenthaltsgenehmigung durch Investitionen sichert',
  'Türkische Immobilien für Familienumzüge',
  'Steuerfreie Immobilieninvestitionen in der Türkei',
  'Eigentumswohnungen in Istanbul für Expats',
  'Schnellverfahren für den türkischen Pass durch Immobilien',
  'Kaufe deine Traumvilla in Istanbul noch heute',
  'Investiere in Istanbuls luxuriöse Villa-Projekte',
  'Entdecke exklusive Immobilien in Bahçeşehir',
  'Starte deine türkische Staatsbürgerschaftsreise mit uns',
  'Erschwingliche Villen zum Verkauf in Istanbul',
  'Kontaktiere uns für Immobiliengeschäfte in Istanbul',
  'Immobilienexperten für die türkische Staatsbürgerschaft',
  'Wie kaufe ich eine Villa in Istanbul als Ausländer',
  'Schritte zum Erwerb der türkischen Staatsbürgerschaft durch Investitionen',
  'Was sind die besten Villa-Projekte in Istanbul 2024?',
  'Ist Immobilieninvestition in der Türkei gut?',
  'Warum Bahçeşehir für Immobilieninvestitionen wählen?',
  'Top Luxusvilla-Projekte zum Verkauf in Istanbul',
  'Türkische Villen zum Verkauf mit Anspruch auf Staatsbürgerschaft',
  'Villen mit privaten Gärten in Istanbul',
  'Häuser mit Balkonen und eigenen Badezimmern',
  'Immobilien mit familienfreundlichen Annehmlichkeiten in Istanbul',
  'Villen mit 24/7 Sicherheitsdienst in Bahçeşehir',
  'Umweltfreundliche Villa-Projekte in Istanbul',
  'Moderne Architektur-Villen in der Türkei',
  'Smart-Home-Villen in Istanbul',
  'Kaufe Luxusvillen in Istanbul für türkische Staatsbürgerschaft',
  'Erschwingliche familienfreundliche Häuser in Bahçeşehir Istanbul',
  'Investitionsmöglichkeiten in Istanbuls beste Villa-Projekte',
  'Villen in Istanbul mit hohem Mietrenditepotenzial',
  'Immobilienexperten für Investitionen in türkische Staatsbürgerschaft'
],
es: [
  'Comprar villas en Sylvana Estambul',
  'Villas 4+1 en Sylvana Estambul en venta',
  'Villas de lujo en Bahçeşehir Estambul',
  'Proyectos de villas modernas en Estambul',
  'Casas de diseño italiano en Sylvana Estambul',
  'Villas en fila en Estambul para familias',
  'Villas cerca del Aeropuerto de Estambul',
  'Inmuebles de alta gama en Bahçeşehir',
  'Villas en Afra Park Estambul en venta',
  'Villas de lujo de 2+1 a 5+1 en Bahçeşehir',
  'Casas familiares en Afra Park',
  'Villas modernas en Bahçeşehir para inversión',
  'Villas de lujo asequibles en Estambul',
  'Propiedades ecológicas en Bahçeşehir',
  'Proyectos de villas en Estambul con comodidades',
  'Villas en Afra Park Bahçeşehir en venta',
  'Propiedades de lujo Reportage Türkiye',
  'Comprar villas modernas en Estambul',
  'Inmuebles en Estambul en venta',
  'Mejores proyectos de villas en Turquía',
  'Desarrollos de villas en Bahçeşehir',
  'Inmuebles cerca de universidades en Estambul',
  'Inversiones en propiedades de lujo en Estambul',
  'Villas en fila y separadas en Estambul',
  'Ciudadanía turca por inversión en inmuebles',
  'Villas para el programa de ciudadanía turca',
  'Propiedades en Estambul para pasaporte turco',
  'Cómo obtener la ciudadanía turca a través de la propiedad',
  'Programa de inversión en ciudadanía turca 2024',
  'Comprar inmuebles en Estambul para la ciudadanía',
  'Villas aprobadas para ciudadanía en Turquía',
  'Inversión mínima para ciudadanía turca',
  'Mejores lugares para invertir en inmuebles en Estambul',
  'Propiedades con alta rentabilidad en Bahçeşehir',
  'Oportunidades de inversión inmobiliaria en Estambul',
  'Mercado inmobiliario de Turquía 2024',
  'Villas para inversión a largo plazo en Estambul',
  'Inversiones de lujo asequibles en Turquía',
  'Inmuebles cerca de grandes proyectos en Estambul',
  'Potencial de ingresos por alquiler en propiedades de Bahçeşehir',
  'Comprar villas en Bahçeşehir Estambul',
  'Propiedades cerca del proyecto del Canal de Estambul',
  'Inmuebles cerca del centro de la ciudad de Başakşehir',
  'Casas cerca de la mega infraestructura de Estambul',
  'Villas cerca de los mejores hospitales de Estambul',
  'Proximidad al nuevo distrito financiero de Estambul',
  'Inmuebles cerca del Nuevo Aeropuerto de Estambul',
  'Beneficios de la ciudadanía turca por inversión',
  'Ventajas de invertir en propiedades en Estambul',
  'Cómo asegurar la residencia turca mediante inversión',
  'Inmuebles en Turquía para reubicación familiar',
  'Inversiones inmobiliarias libres de impuestos en Turquía',
  'Propiedades de propiedad plena en Estambul para expatriados',
  'Pasaporte turco rápido a través de inmuebles',
  'Compra tu villa soñada en Estambul hoy',
  'Invierte en los proyectos de villas de lujo de Estambul',
  'Descubre propiedades exclusivas en Bahçeşehir',
  'Comienza tu viaje hacia la ciudadanía turca con nosotros',
  'Villas asequibles en venta en Estambul',
  'Contáctanos para ofertas inmobiliarias en Estambul',
  'Expertos en bienes raíces para ciudadanía turca',
  'Cómo comprar una villa en Estambul como extranjero',
  'Pasos para adquirir la ciudadanía turca mediante inversión',
  '¿Cuáles son los mejores proyectos de villas en Estambul 2024?',
  '¿Es buena la inversión inmobiliaria en Turquía?',
  '¿Por qué elegir Bahçeşehir para invertir en propiedades?',
  'Proyectos de villas de lujo para la venta en Estambul',
  'Villas turcas en venta con elegibilidad para ciudadanía',
  'Villas con jardines privados en Estambul',
  'Casas con balcones y baños en suite',
  'Propiedades con comodidades familiares en Estambul',
  'Villas con seguridad 24/7 en Bahçeşehir',
  'Proyectos de villas ecológicas en Estambul',
  'Villas con arquitectura moderna en Turquía',
  'Villas inteligentes en Estambul',
  'Comprar villas de lujo en Estambul para obtener ciudadanía turca',
  'Casas familiares asequibles en Bahçeşehir Estambul',
  'Oportunidades de inversión en los mejores proyectos de villas de Estambul',
  'Villas en Estambul con alto potencial de rentabilidad por alquiler',
  'Expertos en bienes raíces para la inversión en ciudadanía turca'
],
fa: [
  'خرید ویلا در سیلوانا استانبول',
  'ویلاهای 4+1 سیلوانا استانبول برای فروش',
  'ویلاهای لوکس در باهچه‌شهر استانبول',
  'پروژه‌های ویلا مدرن در استانبول',
  'خانه‌های طراحی ایتالیایی سیلوانا استانبول',
  'ویلاهای ردیفی در استانبول برای خانواده‌ها',
  'ویلاهای نزدیک به فرودگاه استانبول',
  'املاک لوکس در باهچه‌شهر',
  'ویلاهای آفر پارک استانبول برای فروش',
  'ویلاهای لوکس 2+1 تا 5+1 در باهچه‌شهر',
  'خانه‌های مناسب خانواده‌ها در آفر پارک',
  'ویلاهای مدرن در باهچه‌شهر برای سرمایه‌گذاری',
  'ویلاهای لوکس ارزان در استانبول',
  'املاک دوستدار طبیعت در باهچه‌شهر',
  'پروژه‌های ویلا در استانبول با امکانات',
  'ویلاهای آفر پارک باهچه‌شهر برای فروش',
  'املاک لوکس گزارش ترکیه',
  'خرید ویلاهای مدرن در استانبول',
  'املاک استانبول برای فروش',
  'بهترین پروژه‌های ویلا در ترکیه',
  'توسعه‌های ویلا در باهچه‌شهر',
  'املاک نزدیک به دانشگاه‌های استانبول',
  'سرمایه‌گذاری در املاک لوکس استانبول',
  'ویلاهای ردیفی و جداگانه در استانبول',
  'تابعیت ترکیه از طریق سرمایه‌گذاری در املاک',
  'ویلاها برای برنامه تابعیت ترکیه',
  'املاک استانبول برای پاسپورت ترکیه',
  'چگونه از طریق املاک تابعیت ترکیه بگیریم',
  'برنامه سرمایه‌گذاری تابعیت ترکیه 2024',
  'خرید املاک در استانبول برای تابعیت',
  'ویلاهای تأسیس شده برای تابعیت در ترکیه',
  'حداقل سرمایه‌گذاری برای تابعیت ترکیه',
  'بهترین مکان‌ها برای سرمایه‌گذاری در املاک استانبول',
  'املاک با بازدهی بالا در باهچه‌شهر',
  'فرصت‌های سرمایه‌گذاری در املاک استانبول',
  'بازار املاک ترکیه 2024',
  'ویلاها برای سرمایه‌گذاری بلندمدت در استانبول',
  'سرمایه‌گذاری‌های لوکس ارزان در ترکیه',
  'املاک نزدیک به پروژه‌های عظیم استانبول',
  'پتانسیل درآمد اجاره‌ای در املاک باهچه‌شهر',
  'خرید ویلا در باهچه‌شهر استانبول',
  'املاک نزدیک به پروژه کانال استانبول',
  'املاک نزدیک به مرکز شهر باشاک‌شهر',
  'خانه‌ها نزدیک به زیرساخت‌های عظیم استانبول',
  'ویلاها نزدیک به بهترین بیمارستان‌های استانبول',
  'نزدیکی به منطقه مالی جدید استانبول',
  'املاک نزدیک به فرودگاه جدید استانبول',
  'مزایای تابعیت ترکیه از طریق سرمایه‌گذاری',
  'مزایای سرمایه‌گذاری در املاک استانبول',
  'چگونه می‌توان از طریق سرمایه‌گذاری اقامت ترکیه را دریافت کرد',
  'املاک ترکیه برای جابجایی خانواده‌ها',
  'سرمایه‌گذاری‌های بدون مالیات در املاک ترکیه',
  'املاک آزاد در استانبول برای خارجی‌ها',
  'پاسپورت ترکیه سریع از طریق املاک',
  'امروز ویلا رویایی خود را در استانبول خریداری کنید',
  'در پروژه‌های ویلا لوکس استانبول سرمایه‌گذاری کنید',
  'املاک ویژه در باهچه‌شهر را کشف کنید',
  'سفر تابعیت ترکیه خود را با ما شروع کنید',
  'ویلاهای ارزان برای فروش در استانبول',
  'با ما تماس بگیرید برای معاملات املاک در استانبول',
  'متخصصان املاک در تابعیت ترکیه',
  'چگونه یک ویلا در استانبول به عنوان خارجی خریداری کنیم',
  'مراحل به دست آوردن تابعیت ترکیه از طریق سرمایه‌گذاری',
  'بهترین پروژه‌های ویلا در استانبول 2024 چیست؟',
  'آیا املاک در ترکیه یک سرمایه‌گذاری خوب است؟',
  'چرا باهچه‌شهر را برای سرمایه‌گذاری املاک انتخاب کنیم؟',
  'پروژه‌های ویلا لوکس برای فروش در استانبول',
  'ویلاهای ترکیه‌ای برای فروش با واجد شرایط تابعیت',
  'ویلاهای با باغ‌های خصوصی در استانبول',
  'خانه‌ها با بالکن و حمام‌های اختصاصی',
  'املاک با امکانات مناسب خانواده‌ها در استانبول',
  'ویلاهای با امنیت 24/7 در باهچه‌شهر',
  'پروژه‌های ویلا دوستدار محیط زیست در استانبول',
  'ویلاهای با معماری مدرن در ترکیه',
  'ویلاهای هوشمند در استانبول',
  'خرید ویلاهای لوکس در استانبول برای تابعیت ترکیه',
  'خانه‌های مناسب خانواده‌ها در باهچه‌شهر استانبول',
  'فرصت‌های سرمایه‌گذاری در بهترین پروژه‌های ویلا در استانبول',
  'ویلاهای در استانبول با پتانسیل بالای درآمد اجاره‌ای',
  'متخصصان املاک برای سرمایه‌گذاری تابعیت ترکیه'
],
nl: [
  'Koop villa\'s in Sylvana Istanbul',
  'Sylvana Istanbul 4+1 villa\'s te koop',
  'Luxe villa\'s in Bahçeşehir Istanbul',
  'Moderne villa projecten in Istanbul',
  'Sylvana Istanbul Italiaanse design huizen',
  'Rij villa\'s in Istanbul voor gezinnen',
  'Villa\'s nabij de luchthaven van Istanbul',
  'High-end onroerend goed in Bahçeşehir',
  'Afra Park Istanbul villa\'s te koop',
  'Luxe 2+1 tot 5+1 villa\'s in Bahçeşehir',
  'Gezinsvriendelijke woningen in Afra Park',
  'Moderne villa\'s in Bahçeşehir voor investering',
  'Betaalbare luxe villa\'s in Istanbul',
  'Natuurvriendelijke eigendommen in Bahçeşehir',
  'Villa projecten in Istanbul met voorzieningen',
  'Villa\'s in Afra Park Bahçeşehir te koop',
  'Reportage Türkiye luxe onroerend goed',
  'Koop moderne villa\'s in Istanbul',
  'Onroerend goed in Istanbul te koop',
  'Beste villa projecten in Turkije',
  'Bahçeşehir villa ontwikkelingen',
  'Onroerend goed nabij universiteiten in Istanbul',
  'Luxe onroerend goed investeringen in Istanbul',
  'Rij- en vrijstaande villa\'s in Istanbul',
  'Turkse nationaliteit via onroerend goed investering',
  'Villa\'s voor het Turkse nationaliteitsprogramma',
  'Istanbul onroerend goed voor Turks paspoort',
  'Hoe krijg je de Turkse nationaliteit via onroerend goed',
  'Turks nationaliteitsinvesteringsprogramma 2024',
  'Koop onroerend goed in Istanbul voor nationaliteit',
  'Nationaliteit-goedgekeurde villa\'s in Turkije',
  'Minimale investering voor Turkse nationaliteit',
  'Beste plekken om te investeren in onroerend goed in Istanbul',
  'Eigenschappen met hoge ROI in Bahçeşehir',
  'Investering mogelijkheden in Istanbul onroerend goed',
  'Onroerend goed markt in Turkije 2024',
  'Villa\'s voor lange termijn investering in Istanbul',
  'Betaalbare luxe investeringen in Turkije',
  'Onroerend goed nabij de mega-projecten in Istanbul',
  'Huurinkomstenpotentieel in Bahçeşehir eigendommen',
  'Koop villa\'s in Bahçeşehir Istanbul',
  'Onroerend goed nabij het Istanbul Kanaal project',
  'Onroerend goed nabij Başakşehir stadscentrum',
  'Woningen nabij Istanbul’s mega-infrastructuur',
  'Villa\'s nabij de beste ziekenhuizen in Istanbul',
  'Dichtbij Istanbul’s nieuwe financiële district',
  'Onroerend goed nabij de nieuwe luchthaven van Istanbul',
  'Voordelen van Turkse nationaliteit via investering',
  'Voordelen van investeren in onroerend goed in Istanbul',
  'Hoe krijg je Turkse verblijfsvergunning via investering',
  'Onroerend goed in Turkije voor gezinsverhuizing',
  'Belastingvrije onroerend goed investeringen in Turkije',
  'Onroerend goed in Istanbul voor expats',
  'Snelle Turkse paspoort via onroerend goed',
  'Koop vandaag je droomvilla in Istanbul',
  'Investeer in luxe villa projecten in Istanbul',
  'Ontdek exclusieve eigendommen in Bahçeşehir',
  'Begin je Turkse nationaliteit reis met ons',
  'Betaalbare villa\'s te koop in Istanbul',
  'Neem contact met ons op voor Istanbul onroerend goed deals',
  'Onroerend goed experts in Turkse nationaliteit',
  'Hoe een villa in Istanbul kopen als buitenlander',
  'Stappen om Turkse nationaliteit te verkrijgen via investering',
  'Wat zijn de beste villa projecten in Istanbul 2024?',
  'Is onroerend goed een goede investering in Turkije?',
  'Waarom kiezen voor Bahçeşehir voor onroerend goed investering?',
  'Top luxe villa projecten te koop in Istanbul',
  'Turkse villa\'s te koop met nationaliteitsverklaring',
  'Villa\'s met privé-tuinen in Istanbul',
  'Huizen met balkons en ensuite badkamers',
  'Eigenschappen met gezinsvriendelijke voorzieningen in Istanbul',
  'Villa\'s met 24/7 beveiliging in Bahçeşehir',
  'Eco-vriendelijke villa projecten in Istanbul',
  'Moderne architectuur villa\'s in Turkije',
  'Slimme woning villa\'s in Istanbul',
  'Koop luxe villa\'s in Istanbul voor Turkse nationaliteit',
  'Betaalbare gezinsvriendelijke huizen in Bahçeşehir Istanbul',
  'Investering mogelijkheden in Istanbul\'s top villa projecten',
  'Villa\'s in Istanbul met hoog huurinkomstenpotentieel',
  'Onroerend goed experts voor Turkse nationaliteit investering',
],
ru: [
  'Купите виллы в Сильване Стамбул',
  'Виллы 4+1 в Сильване Стамбул на продажу',
  'Роскошные виллы в Бахчешехире Стамбул',
  'Современные виллы в Стамбуле',
  'Итальянский дизайн домов в Сильване Стамбул',
  'Рядовые виллы в Стамбуле для семей',
  'Виллы рядом с аэропортом Стамбула',
  'Элитная недвижимость в Бахчешехире',
  'Виллы в Афра Парке Стамбул на продажу',
  'Роскошные виллы 2+1 до 5+1 в Бахчешехире',
  'Дома для семей в Афра Парке',
  'Современные виллы в Бахчешехире для инвестиций',
  'Доступные роскошные виллы в Стамбуле',
  'Натуральная недвижимость в Бахчешехире',
  'Проекты вилл в Стамбуле с удобствами',
  'Виллы в Афра Парке Бахчешехир на продажу',
  'Роскошная недвижимость Reportage Türkiye',
  'Купите современные виллы в Стамбуле',
  'Недвижимость в Стамбуле на продажу',
  'Лучшие проекты вилл в Турции',
  'Развитие вилл в Бахчешехире',
  'Недвижимость рядом с университетами Стамбула',
  'Инвестиции в роскошную недвижимость в Стамбуле',
  'Рядовые и отдельно стоящие виллы в Стамбуле',
  'Турецкое гражданство через инвестиции в недвижимость',
  'Виллы для программы турецкого гражданства',
  'Недвижимость в Стамбуле для турецкого паспорта',
  'Как получить турецкое гражданство через недвижимость',
  'Программа инвестиций для турецкого гражданства 2024',
  'Купите недвижимость в Стамбуле для гражданства',
  'Виллы, одобренные для гражданства в Турции',
  'Минимальная инвестиция для турецкого гражданства',
  'Лучшие места для инвестиций в недвижимость в Стамбуле',
  'Объекты с высокой доходностью в Бахчешехире',
  'Возможности для инвестиций в недвижимость в Стамбуле',
  'Недвижимость в Турции 2024',
  'Виллы для долгосрочных инвестиций в Стамбуле',
  'Доступные роскошные инвестиции в Турции',
  'Недвижимость рядом с крупными проектами в Стамбуле',
  'Потенциал дохода от аренды недвижимости в Бахчешехире',
  'Купите виллы в Бахчешехире Стамбул',
  'Недвижимость рядом с проектом Стамбульского канала',
  'Недвижимость рядом с центром города Башакшехир',
  'Дома рядом с крупной инфраструктурой Стамбула',
  'Виллы рядом с лучшими больницами Стамбула',
  'Близость к новому финансовому району Стамбула',
  'Недвижимость рядом с новым аэропортом Стамбула',
  'Преимущества турецкого гражданства через инвестиции',
  'Преимущества инвестирования в недвижимость в Стамбуле',
  'Как получить турецкое резидентство через инвестиции',
  'Недвижимость в Турции для переезда семьи',
  'Безналоговые инвестиции в недвижимость в Турции',
  'Недвижимость в Стамбуле для экспатов',
  'Быстрое получение турецкого паспорта через недвижимость',
  'Купите свою мечту-виллу в Стамбуле сегодня',
  'Инвестируйте в роскошные виллы Стамбула',
  'Откройте для себя эксклюзивную недвижимость в Бахчешехире',
  'Начните свой путь к турецкому гражданству с нами',
  'Доступные виллы на продажу в Стамбуле',
  'Свяжитесь с нами для сделок с недвижимостью в Стамбуле',
  'Эксперты по турецкому гражданству через инвестиции',
  'Как купить виллу в Стамбуле иностранцу',
  'Шаги для получения турецкого гражданства через инвестиции',
  'Какие лучшие проекты вилл в Стамбуле в 2024?',
  'Является ли недвижимость хорошей инвестицией в Турции?',
  'Почему выбрать Бахчешехир для инвестиций в недвижимость?',
  'Топ роскошных проектов вилл на продажу в Стамбуле',
  'Виллы в Турции с правом на гражданство',
  'Виллы с частными садами в Стамбуле',
  'Дома с балконами и ванными комнатами в номере',
  'Недвижимость с удобствами для семей в Стамбуле',
  'Виллы с круглосуточной охраной в Бахчешехире',
  'Экологичные проекты вилл в Стамбуле',
  'Виллы с современной архитектурой в Турции',
  'Умные дома в Стамбуле',
  'Купите роскошные виллы в Стамбуле для турецкого гражданства',
  'Доступные семейные дома в Бахчешехире Стамбул',
  'Возможности инвестиций в лучшие виллы Стамбула',
  'Виллы в Стамбуле с высоким потенциалом арендной платы',
  'Эксперты по инвестициям в турецкое гражданство',
],
tr: [
  'Sylvana İstanbul\'da villa satın alın',
  'Sylvana İstanbul 4+1 villa satışta',
  'Bahçeşehir İstanbul\'da lüks villalar',
  'İstanbul modern villa projeleri',
  'Sylvana İstanbul İtalyan tasarımı evler',
  'İstanbul\'da aileler için sıra villalar',
  'İstanbul Havaalanı yakınlarında villalar',
  'Bahçeşehir yüksek kaliteli emlak',
  'Afra Park İstanbul villaları satışta',
  'Bahçeşehir\'de 2+1 ile 5+1 arasında lüks villalar',
  'Afra Park\'ta aile dostu evler',
  'Bahçeşehir\'de yatırım için modern villalar',
  'İstanbul\'da uygun fiyatlı lüks villalar',
  'Bahçeşehir doğa dostu mülkler',
  'İstanbul\'da olanaklı villa projeleri',
  'Afra Park Bahçeşehir\'de satışta villalar',
  'Reportage Türkiye lüks emlak',
  'İstanbul\'da modern villa satın al',
  'İstanbul\'da satılık emlak',
  'Türkiye\'deki en iyi villa projeleri',
  'Bahçeşehir villa projeleri',
  'İstanbul üniversitelerine yakın emlak',
  'İstanbul\'da lüks emlak yatırımları',
  'İstanbul\'da sıra ve müstakil villalar',
  'Türk vatandaşlığı için gayrimenkul yatırımı',
  'Türk vatandaşlık programı için villalar',
  'Türk pasaportu için İstanbul emlak',
  'Gayrimenkul ile Türk vatandaşlığı nasıl alınır',
  'Türk vatandaşlık yatırım programı 2024',
  'İstanbul\'da gayrimenkul alarak vatandaşlık kazan',
  'Türkiye\'de vatandaşlık onaylı villalar',
  'Türk vatandaşlığı için minimum yatırım',
  'İstanbul\'da emlak yatırımı için en iyi yerler',
  'Bahçeşehir\'de yüksek ROI özellikleri',
  'İstanbul\'da gayrimenkul yatırım fırsatları',
  '2024 Türkiye gayrimenkul pazarı',
  'İstanbul\'da uzun vadeli yatırım için villalar',
  'Türkiye\'de uygun fiyatlı lüks yatırımlar',
  'İstanbul mega projelerine yakın emlak',
  'Bahçeşehir emlaklarında kira geliri potansiyeli',
  'Bahçeşehir İstanbul\'da villa satın al',
  'İstanbul Kanal Projesi yakınlarında emlak',
  'Başakşehir şehir merkezine yakın emlak',
  'İstanbul\'un mega altyapısına yakın evler',
  'İstanbul\'un en iyi hastanelerine yakın villalar',
  'İstanbul yeni finansal bölgesine yakınlık',
  'İstanbul Yeni Havaalanı yakınlarında emlak',
  'Türk vatandaşlığı ile yatırımın avantajları',
  'İstanbul\'da emlak yatırımı yapmanın avantajları',
  'Yatırım yaparak Türk oturumu nasıl alınır',
  'Aile göçü için Türk gayrimenkulü',
  'Türkiye\'de vergi muafiyetli emlak yatırımları',
  'İstanbul\'da yabancılara ait mülkler',
  'Emlak aracılığıyla Türk pasaportu hızlı alım',
  'Bugün İstanbul\'da hayalinizdeki villayı satın alın',
  'İstanbul\'un lüks villa projelerine yatırım yapın',
  'Bahçeşehir\'deki özel mülkleri keşfedin',
  'Türk vatandaşlık yolculuğunuza bizimle başlayın',
  'İstanbul\'da satılık uygun fiyatlı villalar',
  'İstanbul\'da emlak anlaşmaları için bizimle iletişime geçin',
  'Türk vatandaşlığına yatırım uzmanları',
  'Yabancı olarak İstanbul\'da villa nasıl satın alınır',
  'Türk vatandaşlığı için yatırım adımları',
  '2024\'te İstanbul\'da en iyi villa projeleri nedir?',
  'Türkiye\'de emlak yatırımı iyi bir seçenek mi?',
  'Bahçeşehir\'de neden emlak yatırımı yapmalısınız?',
  'İstanbul\'da satılık en iyi lüks villa projeleri',
  'Türk vatandaşlığına uygun satılık villalar',
  'İstanbul\'da özel bahçeli villalar',
  'Balkonlu ve ebeveyn banyolu evler',
  'İstanbul\'da aile dostu imkanlara sahip mülkler',
  'Bahçeşehir\'de 7/24 güvenlikli villalar',
  'İstanbul\'da çevre dostu villa projeleri',
  'Türkiye\'de modern mimari villalar',
  'İstanbul\'da akıllı evler',
  'Türk vatandaşlığı için İstanbul\'da lüks villa satın al',
  'Bahçeşehir İstanbul\'da uygun fiyatlı aile dostu evler',
  'İstanbul\'un en iyi villa projelerinde yatırım fırsatları',
  'İstanbul\'daki villalar yüksek kiralama getirisi potansiyeli',
  'Türk vatandaşlığı yatırım uzmanları',
],
zh: [
  '在Sylvana伊斯坦布尔购买别墅',
  'Sylvana伊斯坦布尔4+1别墅出售',
  '巴赫切谢希尔伊斯坦布尔豪华别墅',
  '伊斯坦布尔现代别墅项目',
  'Sylvana伊斯坦布尔意大利设计住宅',
  '伊斯坦布尔家庭排屋别墅',
  '靠近伊斯坦布尔机场的别墅',
  '巴赫切谢希尔高端房地产',
  'Afra Park伊斯坦布尔别墅出售',
  '巴赫切谢希尔2+1到5+1豪华别墅',
  'Afra Park家庭友好住宅',
  '巴赫切谢希尔投资现代别墅',
  '伊斯坦布尔实惠的豪华别墅',
  '巴赫切谢希尔环保型房产',
  '伊斯坦布尔带有设施的别墅项目',
  'Afra Park巴赫切谢希尔出售别墅',
  'Reportage Türkiye豪华房产',
  '在伊斯坦布尔购买现代别墅',
  '伊斯坦布尔房地产出售',
  '土耳其最佳别墅项目',
  '巴赫切谢希尔别墅开发项目',
  '靠近伊斯坦布尔大学的房地产',
  '伊斯坦布尔豪华房地产投资',
  '伊斯坦布尔排屋和独栋别墅',
  '通过房地产投资获得土耳其公民身份',
  '土耳其公民身份计划的别墅',
  '伊斯坦布尔房地产用于土耳其护照',
  '如何通过房地产获得土耳其公民身份',
  '土耳其公民身份投资计划2024',
  '在伊斯坦布尔购买房地产获得公民身份',
  '土耳其公民身份认证别墅',
  '土耳其公民身份最低投资额',
  '伊斯坦布尔最佳房地产投资地点',
  '巴赫切谢希尔高回报投资房产',
  '伊斯坦布尔房地产投资机会',
  '2024土耳其房地产市场',
  '伊斯坦布尔长期投资的别墅',
  '土耳其实惠的豪华投资',
  '靠近伊斯坦布尔重大项目的房地产',
  '巴赫切谢希尔房产的租金收入潜力',
  '在巴赫切谢希尔伊斯坦布尔购买别墅',
  '靠近伊斯坦布尔运河项目的房产',
  '靠近巴萨克谢希尔市中心的房地产',
  '靠近伊斯坦布尔大型基础设施的房屋',
  '靠近伊斯坦布尔顶级医院的别墅',
  '靠近伊斯坦布尔新金融区的房产',
  '靠近伊斯坦布尔新机场的房产',
  '通过投资获得土耳其公民身份的好处',
  '投资伊斯坦布尔房产的优势',
  '如何通过投资获得土耳其居留权',
  '为家庭搬迁选择土耳其房地产',
  '在土耳其免税房地产投资',
  '适合外国人的伊斯坦布尔永久产权房产',
  '通过房地产快速获得土耳其护照',
  '今天购买您梦想中的伊斯坦布尔别墅',
  '投资伊斯坦布尔的豪华别墅项目',
  '发现巴赫切谢希尔的独家房产',
  '与我们一起开始您的土耳其公民身份之旅',
  '在伊斯坦布尔购买实惠的别墅',
  '联系我们获取伊斯坦布尔房地产优惠',
  '土耳其公民身份投资专家',
  '外国人如何在伊斯坦布尔购买别墅',
  '通过投资获得土耳其公民身份的步骤',
  '2024年伊斯坦布尔最佳别墅项目是什么？',
  '土耳其的房地产投资值得吗？',
  '为什么选择巴赫切谢希尔进行房地产投资？',
  '伊斯坦布尔最好的豪华别墅项目',
  '适合土耳其公民身份的土耳其别墅',
  '带私人花园的伊斯坦布尔别墅',
  '带阳台和套间浴室的房屋',
  '伊斯坦布尔适合家庭的房地产',
  '巴赫切谢希尔24小时安保别墅',
  '伊斯坦布尔环保别墅项目',
  '土耳其现代建筑别墅',
  '伊斯坦布尔智能家居别墅',
  '为土耳其公民身份购买伊斯坦布尔豪华别墅',
  '巴赫切谢希尔伊斯坦布尔适合家庭的实惠住房',
  '伊斯坦布尔顶级别墅项目的投资机会',
  '伊斯坦布尔的别墅具有高租金收益潜力',
  '土耳其公民身份投资的房地产专家',
],
fr: [
  'Achetez des villas à Sylvana Istanbul',
  'Villas 4+1 à vendre à Sylvana Istanbul',
  'Villas de luxe à Bahçeşehir Istanbul',
  'Projets de villas modernes à Istanbul',
  'Maisons au design italien à Sylvana Istanbul',
  'Villas en rangée à Istanbul pour les familles',
  'Villas près de l\'aéroport d\'Istanbul',
  'Immobilier haut de gamme à Bahçeşehir',
  'Villas à vendre à Afra Park Istanbul',
  'Villas de luxe 2+1 à 5+1 à Bahçeşehir',
  'Maisons familiales à Afra Park',
  'Villas modernes à Bahçeşehir pour investissement',
  'Villas de luxe abordables à Istanbul',
  'Propriétés respectueuses de l\'environnement à Bahçeşehir',
  'Projets de villas à Istanbul avec des commodités',
  'Villas à vendre à Afra Park Bahçeşehir',
  'Propriétés de luxe Reportage Türkiye',
  'Achetez des villas modernes à Istanbul',
  'Immobilier à vendre à Istanbul',
  'Meilleurs projets de villas en Turquie',
  'Développements de villas à Bahçeşehir',
  'Immobilier près des universités d\'Istanbul',
  'Investissements immobiliers de luxe à Istanbul',
  'Villas en rangée et villas individuelles à Istanbul',
  'Citoyenneté turque par investissement immobilier',
  'Villas pour le programme de citoyenneté turque',
  'Propriétés à Istanbul pour passeport turc',
  'Comment obtenir la citoyenneté turque par l\'immobilier',
  'Programme d\'investissement pour la citoyenneté turque 2024',
  'Achetez de l\'immobilier à Istanbul pour la citoyenneté',
  'Villas approuvées pour la citoyenneté en Turquie',
  'Investissement minimum pour la citoyenneté turque',
  'Meilleurs endroits pour investir dans l\'immobilier à Istanbul',
  'Propriétés à fort rendement à Bahçeşehir',
  'Opportunités d\'investissement immobilier à Istanbul',
  'Marché immobilier turc 2024',
  'Villas pour un investissement à long terme à Istanbul',
  'Investissements abordables en Turquie',
  'Immobilier près des grands projets d\'Istanbul',
  'Potentiel de revenu locatif des propriétés à Bahçeşehir',
  'Achetez des villas à Bahçeşehir Istanbul',
  'Propriétés près du projet du canal d\'Istanbul',
  'Immobilier près du centre-ville de Başakşehir',
  'Maisons près des grandes infrastructures d\'Istanbul',
  'Villas près des meilleurs hôpitaux d\'Istanbul',
  'Proximité du nouveau quartier financier d\'Istanbul',
  'Immobilier près du nouvel aéroport d\'Istanbul',
  'Avantages de la citoyenneté turque par investissement',
  'Avantages d\'investir dans l\'immobilier à Istanbul',
  'Comment sécuriser la résidence turque par investissement',
  'Immobilier turc pour les familles en relocation',
  'Investissements immobiliers exonérés d\'impôts en Turquie',
  'Propriétés en pleine propriété à Istanbul pour les expatriés',
  'Passeport turc accéléré par l\'immobilier',
  'Achetez la villa de vos rêves à Istanbul aujourd\'hui',
  'Investissez dans les projets de villas de luxe à Istanbul',
  'Découvrez des propriétés exclusives à Bahçeşehir',
  'Commencez votre parcours vers la citoyenneté turque avec nous',
  'Villas abordables à vendre à Istanbul',
  'Contactez-nous pour des offres immobilières à Istanbul',
  'Experts immobiliers en citoyenneté turque',
  'Comment acheter une villa à Istanbul en tant qu\'étranger',
  'Étapes pour acquérir la citoyenneté turque par investissement',
  'Quels sont les meilleurs projets de villas à Istanbul en 2024 ?',
  'L\'immobilier est-il un bon investissement en Turquie ?',
  'Pourquoi choisir Bahçeşehir pour un investissement immobilier ?',
  'Meilleurs projets de villas de luxe à vendre à Istanbul',
  'Villas turques à vendre avec éligibilité à la citoyenneté',
  'Villas avec jardins privés à Istanbul',
  'Maisons avec balcons et salles de bains attenantes',
  'Propriétés avec des commodités familiales à Istanbul',
  'Villas avec sécurité 24/7 à Bahçeşehir',
  'Projets de villas écologiques à Istanbul',
  'Villas à architecture moderne en Turquie',
  'Villas intelligentes à Istanbul',
  'Achetez des villas de luxe à Istanbul pour la citoyenneté turque',
  'Maisons familiales abordables à Bahçeşehir Istanbul',
  'Opportunités d\'investissement dans les meilleurs projets de villas à Istanbul',
  'Villas à Istanbul avec fort potentiel de rendement locatif',
  'Experts immobiliers pour l\'investissement en citoyenneté turque',
]

  // Other language translations here...
};

// Server-side translations
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}

export default function Home() {
  const { t, i18n } = useTranslation('common');
  const language = i18n.language;
  const keywords = keywordsByLanguage[language]?.join(', ') || '';

  return (
    <>
      <Head>
        {/* Primary SEO Meta Tags */}
        <title>{t('home.title')}</title>
        <meta name="description" content={t('home.description')} />
        <meta name="keywords" content={keywords} />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

        {/* Open Graph Meta Tags for Social Sharing */}
        <meta property="og:title" content={t('home.title')} />
        <meta property="og:description" content={t('home.description')} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://example.com" />
        <meta property="og:image" content="/assets/images/social-image.webp" />

        {/* Preload Key Fonts */}
        <link rel="preload" href="/fonts/custom-font.woff2" as="font" type="font/woff2" crossorigin="anonymous" />

        {/* Structured Data for Enhanced SEO */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "RealEstateListing",
            "name": t('home.title'),
            "description": t('home.description'),
            "keywords": keywords,
            "offers": [
              {
                "@type": "Offer",
                "name": "Sylvana Istanbul",
                "availability": "InStock",
                "priceCurrency": "USD",
              },
              {
                "@type": "Offer",
                "name": "Afra Park Bahçeşehir",
                "availability": "InStock",
                "priceCurrency": "USD",
              },
              {
                "@type": "Offer",
                "name": "Arabian Ranches",
                "availability": "InStock",
                "priceCurrency": "USD",
              },
            ],
          })}
        </script>
      </Head>

      <main className="flex-grow container mx-auto pt-16 pb-16 space-y-12 px-4 md:px-8">
        {/* Hero Section */}
        <section aria-labelledby="hero-section">
          <Suspense fallback={<div>Loading Hero...</div>}>
            <Hero />
          </Suspense>
        </section>

        {/* Globe Component */}
        <section className="py-12" aria-labelledby="globe-section">
          <Suspense fallback={<div>Loading Globe...</div>}>
            <Globe />
          </Suspense>
        </section>

        {/* Hero Title and Subtitle with Keywords */}
        <section className="text-center my-8" aria-labelledby="hero-title">
          <h1 id="hero-title" className="text-3xl font-bold">
            {t('hero_title.title')} - {t('hero_title.subtitle')}
          </h1>
          <p id="hero-subtitle" className="mt-4 text-lg" aria-describedby="hero-title">
            {t('hero_description')}
          </p>
        </section>

        {/* Home Page Content Section */}
        <section id="home-page-content" className="py-12" aria-labelledby="home-page-content">
          <Suspense fallback={<div>Loading Content...</div>}>
            <HomePageContent />
          </Suspense>
        </section>

        {/* Filter Component Section */}
        <section id="filter-section" className="py-12" aria-labelledby="filter-section">
          <Suspense fallback={<div>Loading Project Designs...</div>}>
            <Filter />
          </Suspense>
        </section>

        {/* Mobile Gallery Section */}
        <section id="mobile-gallery-section" className="py-12" aria-labelledby="mobile-gallery-section">
          <Suspense fallback={<div>Loading Gallery...</div>}>
            <MobileGallery />
          </Suspense>
        </section>

        {/* FAQ Section */}
        <section id="faq-section" className="py-12" aria-labelledby="faq-section">
          <Suspense fallback={<div>Loading FAQ...</div>}>
            <Faq />
          </Suspense>
        </section>

        {/* Contact Section */}
        <section id="contact-section" className="py-12" aria-labelledby="contact-section">
          <Suspense fallback={<div>Loading Contact...</div>}>
            <Contact />
          </Suspense>
        </section>
      </main>
    </>
  );
}
